namespace Lugh.Logging;

public enum SystemMeters
{
    _ILLEGAL_GAME_MODE = 0,
    _SOUND_LOAD_FAIL,
    _BAD_PLAYER_ACTION,
    _FONT_LOAD_FAILURE,
    _BORDERED_FONT_LOAD_FAILURE,

    _IO_EXCEPTION,
    _INDEX_OUT_OF_BOUNDS_EXCEPTION,
    _ARRAY_INDEX_OUT_OF_BOUNDS_EXCEPTION,
    _SAX_EXCEPTION,
    _INTERRUPTED_EXCEPTION,
    _NULL_POINTER_EXCEPTION,
    _ILLEGAL_STATE_EXCEPTION,
    _GDX_RUNTIME_EXCEPTION,
    _ENTITY_DATA_EXCEPTION,

    _UNKNOWN_EXCEPTION,
    _DUMMY_METER,

    _MAX_SYSTEM_METERS,
}